APP_VERSION = "KONTROLNA"

# text size
START_TITLE_TEXT_SIZE = "60px"
START_INSTRUCTION_BUTTON_TEXT_SIZE = "20px"

START_INSTRUCTION_TITLE_TEXT_SIZE = "60px"
START_INSTRUCTION_TEXT_SIZE = "35px"

TOP_LABEL_TEXT_SIZE = "90px"
BOTTOM_LABELS_TEXT_SIZE = "35px"
END_PAGE_TEXT_SIZE = "50px"

# text color
_text_color = "#445566"
START_TITLE_TEXT_COLOR = _text_color

START_INSTRUCTION_TITLE_TEXT_COLOR = _text_color
START_INSTRUCTION_TEXT_COLOR = _text_color
START_INSTRUCTION_BUTTON_TEXT_COLOR = _text_color
TOP_LABEL_TEXT_COLOR = _text_color
BOTTOM_LABELS_TEXT_COLOR = _text_color
END_PAGE_TEXT_COLOR = _text_color
SELECTED_ANSWER_TEXT_COLOR = "#00FF00"
CORRECT_ANSWER_BG_COLOR = "#00FF00"
WRONG_ANSWER_BG_COLOR = "#FF0000"

# color
_bg_color = "#AABBCC"
OK_BUTTON_BG_COLOR = "#99AABB"
INSTRUCTION_BORDER_COLOR = "#8899AA"
APP_BACKGROUND_COLOR = _bg_color
TOP_LABEL_BACKGROUND_COLOR = _bg_color
ANSWERS_LABELS_BG_COLOR = "#CCDDEE"
PHOTO_FRAME_COLOR = "#000000"
